title: DaLei-Blog
description: "A Tech Blog Theme For DaLei"
author:
  name: "DaLei"
  email: "wangcppclei@gmail.com"
  url: "https://wangdalei.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "DaLei"
year : "2019"
